[target.x86_64-pc-windows-msvc.'usb-1.0']
rustc-link-search = ["/lib/MS64/static"]
rustc-link-lib = ["usb-1.0"]

[target.x86_32-pc-windows-msvc.'usb-1.0']
rustc-link-search = ["/lib/MS32/static"]
rustc-link-lib = ["usb-1.0"]

[target.x86_64-pc-windows-gnu.'usb-1.0']
rustc-link-search = ["/lib/MinGW64/static"]
rustc-link-lib = ["usb-1.0"]

[target.x86_32-pc-windows-gnu.'usb-1.0']
rustc-link-search = ["/lib/MinGW32/static"]
rustc-link-lib = ["usb-1.0"]
